name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java JDK (if needed for Maven to build the project)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t dhirajvarma4158/spring-petclinic-main:${{ github.sha }} .

      # Step 4: Log in to Docker Hub (or GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password in GitHub Secrets

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push dhirajvarma4158/spring-petclinic-main:${{ github.sha }}

      # Step 6 (Optional): Tag the image with the 'latest' tag and push it
      - name: Tag and push Docker image as 'latest'
        run: |
          docker tag dhirajvarma4158/spring-petclinic-main:${{ github.sha }} dhirajvarma4158/spring-petclinic-main:latest
          docker push dhirajvarma4158/spring-petclinic-main:latest
